"""empty message

Revision ID: 3e7050090d3a
Revises: 27e00f25f0a4
Create Date: 2025-11-15 16:54:31.315406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7050090d3a'
down_revision = '27e00f25f0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=False))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('can_modify')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_modify', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
