"""Edit column name

Revision ID: a64e94a7ca71
Revises: 5ab77dbf94ec
Create Date: 2025-11-13 15:55:31.841020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64e94a7ca71'
down_revision = '5ab77dbf94ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_modify', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('admin')
        batch_op.drop_column('canModify')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canModify', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('can_modify')

    # ### end Alembic commands ###
